//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public  class Comment
    {
        public int Id { get; set; }

        public string Username { get; set; }

        public string EventType { get; set; }

        public int EventId { get; set; }

        public string Comments { get; set; }

        public DateTime Date { get; set; }

    }
}
