//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public class CultureEvent
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public DateTime Date { get; set; }
        public string PhoneNumber { get; set; }
        public string EMail { get; set; }
        public string Organizer { get; set; }
        public string Street { get; set; }

        public string Creator { get; set; }

    }
}
