//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class SelfTaugthEvent
    {

        public int Id { get; set; }
        public string EventName { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string Activity { get; set; }

        public string Street { get; set; }

        public string Creator { get; set; }

    }
}
