//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class SportEvent
    {
        public int Id { get; set; }
        [Required]
        public string EventName { get; set; }
        public string ImagePath { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
        [Required]
        public string Street { get; set; }

        public string Creator { get; set; }
    }
}
